version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/Scalify/gitlab-project-settings-state-enforcer

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: install dependencies
          command: |
            curl https://glide.sh/get | sh
            glide install --strip-vendor

      - run:
          name: run tests
          command: go test -v ./...

      - run:
          name: gometalinter
          command: |
            go get github.com/alecthomas/gometalinter
            gometalinter -i
            gometalinter --deadline=5m --vendor --skip=proto --sort=severity ./...

  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/Scalify/gitlab-project-settings-state-enforcer

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - deploy:
          name: push docker images
          command: |
            [ "${CIRCLE_BRANCH}" != "master" ] && [ -z "${CIRCLE_TAG}" ] && exit 0

            export DOCKER_REPO=$(echo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" | awk '{print tolower($0)}')

            docker login -u ${DOCKER_USER} -p "${DOCKER_PASS}" https://index.docker.io/v1/
            docker build -t ${DOCKER_REPO} .

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push ${DOCKER_REPO}
            fi

            if [ -n "${CIRCLE_TAG}" ]; then
              docker tag ${DOCKER_REPO} ${DOCKER_REPO}:${CIRCLE_TAG}
              docker push ${DOCKER_REPO}:${CIRCLE_TAG}
            fi

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          context: docker
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
